"use strict";
exports.__esModule = true;
exports.app = void 0;
var express_1 = require("express");
var cors_1 = require("cors");
var router_1 = require("./router");
var db_1 = require("./db");
var app = (0, express_1["default"])();
exports.app = app;
app.use((0, cors_1["default"])());
app.use(express_1["default"].json());
app.use("/api", router_1.router);
db_1.db.sync();
app.listen(3333, function () { return console.log("Server started on port 3333"); });
